### ISSUE TITLE
Execute `ldconfig` after installing

### ISSUE THREAD

**Issue by michaelarnauts** [AnsgarSchmidt/Mosquitto#4]
`/sbin/ldconfig` has to be ran as root after installing mosquitto. This makes sure that `mosquitto_sub` knows where `libmosquitto.so.1` is located.

Without `ldconfig`, executed in the container.

``` shell
$ mosquitto_sub -h localhost -t "#"               
mosquitto_sub: error while loading shared libraries: libmosquitto.so.1: cannot open shared object file: No such file or directory
```

**Comment by AnsgarSchmidt** [comment]
Merged the pull request
